package cn.read.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.read.bean.NewsChannelTable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NEWS_CHANNEL_TABLE".
*/
public class NewsChannelTableDao extends AbstractDao<NewsChannelTable, String> {

    public static final String TABLENAME = "NEWS_CHANNEL_TABLE";

    /**
     * Properties of entity NewsChannelTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property TableId = new Property(0, String.class, "tableId", true, "TABLE_ID");
        public final static Property NewsChannelName = new Property(1, String.class, "newsChannelName", false, "NEWS_CHANNEL_NAME");
        public final static Property NewsChannelId = new Property(2, String.class, "newsChannelId", false, "NEWS_CHANNEL_ID");
        public final static Property NewsChannelType = new Property(3, String.class, "newsChannelType", false, "NEWS_CHANNEL_TYPE");
        public final static Property NewsChannelSelect = new Property(4, boolean.class, "newsChannelSelect", false, "NEWS_CHANNEL_SELECT");
        public final static Property NewsChannelIndex = new Property(5, int.class, "newsChannelIndex", false, "NEWS_CHANNEL_INDEX");
        public final static Property NewsChannelFixed = new Property(6, Boolean.class, "newsChannelFixed", false, "NEWS_CHANNEL_FIXED");
    };


    public NewsChannelTableDao(DaoConfig config) {
        super(config);
    }
    
    public NewsChannelTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEWS_CHANNEL_TABLE\" (" + //
                "\"TABLE_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: tableId
                "\"NEWS_CHANNEL_NAME\" TEXT NOT NULL ," + // 1: newsChannelName
                "\"NEWS_CHANNEL_ID\" TEXT NOT NULL ," + // 2: newsChannelId
                "\"NEWS_CHANNEL_TYPE\" TEXT NOT NULL ," + // 3: newsChannelType
                "\"NEWS_CHANNEL_SELECT\" INTEGER NOT NULL ," + // 4: newsChannelSelect
                "\"NEWS_CHANNEL_INDEX\" INTEGER NOT NULL ," + // 5: newsChannelIndex
                "\"NEWS_CHANNEL_FIXED\" INTEGER);"); // 6: newsChannelFixed
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEWS_CHANNEL_TABLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NewsChannelTable entity) {
        stmt.clearBindings();
 
        String tableId = entity.getTableId();
        if (tableId != null) {
            stmt.bindString(1, tableId);
        }
        stmt.bindString(2, entity.getNewsChannelName());
        stmt.bindString(3, entity.getNewsChannelId());
        stmt.bindString(4, entity.getNewsChannelType());
        stmt.bindLong(5, entity.getNewsChannelSelect() ? 1L: 0L);
        stmt.bindLong(6, entity.getNewsChannelIndex());
 
        Boolean newsChannelFixed = entity.getNewsChannelFixed();
        if (newsChannelFixed != null) {
            stmt.bindLong(7, newsChannelFixed ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NewsChannelTable entity) {
        stmt.clearBindings();
 
        String tableId = entity.getTableId();
        if (tableId != null) {
            stmt.bindString(1, tableId);
        }
        stmt.bindString(2, entity.getNewsChannelName());
        stmt.bindString(3, entity.getNewsChannelId());
        stmt.bindString(4, entity.getNewsChannelType());
        stmt.bindLong(5, entity.getNewsChannelSelect() ? 1L: 0L);
        stmt.bindLong(6, entity.getNewsChannelIndex());
 
        Boolean newsChannelFixed = entity.getNewsChannelFixed();
        if (newsChannelFixed != null) {
            stmt.bindLong(7, newsChannelFixed ? 1L: 0L);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public NewsChannelTable readEntity(Cursor cursor, int offset) {
        NewsChannelTable entity = new NewsChannelTable( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // tableId
            cursor.getString(offset + 1), // newsChannelName
            cursor.getString(offset + 2), // newsChannelId
            cursor.getString(offset + 3), // newsChannelType
            cursor.getShort(offset + 4) != 0, // newsChannelSelect
            cursor.getInt(offset + 5), // newsChannelIndex
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0 // newsChannelFixed
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NewsChannelTable entity, int offset) {
        entity.setTableId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setNewsChannelName(cursor.getString(offset + 1));
        entity.setNewsChannelId(cursor.getString(offset + 2));
        entity.setNewsChannelType(cursor.getString(offset + 3));
        entity.setNewsChannelSelect(cursor.getShort(offset + 4) != 0);
        entity.setNewsChannelIndex(cursor.getInt(offset + 5));
        entity.setNewsChannelFixed(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
     }
    
    @Override
    protected final String updateKeyAfterInsert(NewsChannelTable entity, long rowId) {
        return entity.getTableId();
    }
    
    @Override
    public String getKey(NewsChannelTable entity) {
        if(entity != null) {
            return entity.getTableId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
